### ISSUE TITLE
meet BrokenPipeError while extract_keyphrases, are there steps wrong?

### ISSUE THREAD

**Issue by penolove** [swisscom/ai-research-keyphrase-extraction#7]
I try following command and meet BrokenPipeError
```
docker build . -t keyphrase-extraction
docker run -v torontobooks_bigrams.bin:/sent2vec/pretrained_model.bin -it keyphrase-extraction
```
in docker 
```
import launch

embedding_distributor = launch.load_local_embedding_distributor('en')
pos_tagger = launch.load_local_pos_tagger('en')
raw_text = 'this is the text i want to extract keyphrases from'
kp1 = launch.extract_keyphrases(embedding_distributor, pos_tagger, raw_text, 10, 'en') 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/launch.py", line 29, in extract_keyphrases
    return MMRPhrase(embedding_distrib, text_obj, N=N, beta=beta, alias_threshold=alias_threshold)
  File "/app/swisscom_ai/research_keyphrase/model/method.py", line 87, in MMRPhrase
    candidates, X = extract_candidates_embedding_for_doc(embdistrib, text_obj)
  File "/app/swisscom_ai/research_keyphrase/model/methods_embeddings.py", line 44, in extract_candidates_embedding_for_doc
    embeddings = np.array(embedding_distrib.get_tokenized_sents_embeddings(candidates))  # Associated embeddings
  File "/app/swisscom_ai/research_keyphrase/embeddings/emb_distrib_local.py", line 41, in get_tokenized_sents_embeddings
    self._stdin_handle.flush()
BrokenPipeError: [Errno 32] Broken pipe

**Comment by kamilbs** [comment]
Hello , thanks for your interest :)  did you allowed enough memory (the models are heavy) to your docker container ? By allowing more memory you'll certainly remove this error.
